const FORM_URL='https://forms.gle/msXn5jNgMF3Aet3N9';
const listings=[
 {num:1,name:'Adams Family Haunt',town:'Budd Lake',address:'5 N Mount Olive Rd, Budd Lake, NJ',dates:'Now through Halloween',times:'4:00 PM–8:00 PM',levels:['Family Friendly','Spooky','Scary'],type:['Walk-through'],features:['Animatronics','Fog','Music/Sound','Photo Opportunities'],notes:"Skully's Costume Closet is open daily 6:00–8:00 PM and weekends 10:00 AM–6:00 PM through Halloween. Free costumes & goodies."},
 {num:2,name:'Alcrest Avenue Halloween Display',town:'Budd Lake',address:'24 Alcrest Avenue, Budd Lake, NJ',dates:'Halloween weekend',times:'All weekend',levels:[],type:[],features:['Spider theme'],notes:'More details coming soon.'},
 {num:3,name:'Fifth Street Halloween Display',town:'Budd Lake',address:'23 Fifth Street, Budd Lake, NJ',dates:'',times:'',levels:['Family Friendly'],type:['Drive-by','Walk-up'],features:[],notes:'More details coming soon.'},
 {num:4,name:"Snowba's Graveyard",town:'Stanhope',address:'13 Towpath Lane, Stanhope, NJ',dates:'Anytime',times:'Lights turn on at 6:00 PM',levels:[],type:[],features:['Spooky decor','Lights','Animatronics'],notes:''},
 {num:5,name:'Rose Lane Halloween Display',town:'Budd Lake',address:'9 Rose Lane, Budd Lake, NJ',dates:'Halloween',times:'',levels:[],type:[],features:[],notes:'Display will be decorated for Halloween. More details coming soon.'},
 {num:6,name:"Will's House of Horrors",town:'Flanders',address:'20 Tinc Rd, Flanders, NJ',dates:'October',times:'Fri–Sun 6:00 PM–12:00 AM · Mon–Thu 6:00 PM–11:00 PM',levels:['Spooky','Scary'],type:['Walk-up'],features:['Animatronics','Spooky Decor','Fog','Lights','Yard Display'],notes:'Front yard lights on nightly during October. willshouseofhorrors.com'},
 {num:7,name:'Sunset Drive Halloween Display',town:'Budd Lake',address:'14 Sunset Dr, Budd Lake, NJ',dates:'Expected complete this weekend',times:'',levels:[],type:['Drive-by'],features:[],notes:'Display is still in progress and should be completed this weekend.'}
];
const filters=['All','Family Friendly','Spooky','Scary','Walk-through','Drive-by','Animatronics'];
const state={filter:'All',selected:null,route:[],startMode:'current',startAddr:'',coords:{}};

try{const saved=JSON.parse(localStorage.getItem('hfroute:2026')||'[]');if(Array.isArray(saved))state.route=[...new Set(saved.filter(n=>listings.some(x=>x.num===n)))]}catch{}

const map=L.map('map',{scrollWheelZoom:true,dragging:!L.Browser.mobile,tap:true}).setView([40.87,-74.72],12);
L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer/tile/{z}/{y}/{x}',{maxZoom:16,attribution:'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ'}).addTo(map);
const markerByNum=new Map();

function pinHTML(n){return `<div class="pin" data-pin="${n}"><span class="pin__ring"></span><img src="pumpkin-pin.svg" alt=""><span class="pin__num">${n}</span><span class="pin__check">✓</span></div>`}
function iconFor(n){return L.divIcon({className:'',html:pinHTML(n),iconSize:[58,68],iconAnchor:[29,68]})}
function gmapsDirections(address){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(address)}`}
function matchFilter(x){if(state.filter==='All')return true;if(['Family Friendly','Spooky','Scary'].includes(state.filter))return x.levels.includes(state.filter);if(['Walk-through','Drive-by'].includes(state.filter))return x.type.includes(state.filter);if(state.filter==='Animatronics')return x.features.includes('Animatronics');return true}
function scarePips(levels){const order=['Family Friendly','Spooky','Scary'];return `<span class="pips">${order.map(x=>`<span class="pip ${levels.includes(x)?'is-on':''}"></span>`).join('')}</span>${levels.length?levels.join(' · '):'Not specified'}`}
function cardHTML(x){const selected=state.selected===x.num,onRoute=state.route.includes(x.num);return `<article class="card ${selected?'is-selected':''}" data-card="${x.num}" tabindex="0" aria-label="${x.name}"><div class="card__head"><div class="card__pin">${pinHTML(x.num)}</div><div class="card__heading"><div class="card__title-row"><h3 class="card__name">${x.name}</h3><button type="button" class="card-rating" data-feedback="${x.num}" data-rating-summary="${x.num}" aria-label="View ratings for ${x.name}">No ratings yet</button></div><div class="card__town">${x.town}</div></div></div><dl class="card__facts"><dt>Where</dt><dd>${x.address}</dd><dt>When</dt><dd>${[x.dates,x.times].filter(Boolean).join(' · ')||'Not specified'}</dd><dt>Scare</dt><dd>${scarePips(x.levels)}</dd><dt>Type</dt><dd>${x.type.length?x.type.join(' · '):'Not specified'}</dd></dl><div class="chips">${x.features.map(f=>`<span class="chip">${f}</span>`).join('')}</div><div class="card__notes"><strong>Notes from the host</strong>${x.notes||'No additional notes yet.'}</div><div class="card__actions"><button class="btn btn--route" type="button" data-route="${x.num}" aria-pressed="${onRoute}">${onRoute?'Added ✓':'+ Add to Route'}</button><a class="btn btn--directions" href="${gmapsDirections(x.address)}" target="_blank" rel="noopener" onclick="event.stopPropagation()">Directions ↗</a><button class="btn btn--feedback" type="button" data-feedback="${x.num}" aria-haspopup="dialog">Leave / View Feedback</button><button class="btn btn--feedback" type="button" data-share-house="${x.num}" aria-haspopup="dialog">Share this house</button></div></article>`}

function renderFilters(){document.getElementById('filters').innerHTML=filters.map(f=>`<button class="filter" type="button" data-filter="${f}" aria-pressed="${state.filter===f}">${f}</button>`).join('')}
function renderCards(){const visible=listings.filter(matchFilter);document.getElementById('countLine').textContent=`${visible.length} display${visible.length===1?'':'s'} shown${state.filter!=='All'?' · '+state.filter:''}`;document.getElementById('cardList').innerHTML=visible.map(cardHTML).join('');document.getElementById('noResults').classList.toggle('is-hidden',visible.length>0);document.getElementById('noResultsText').textContent=`No displays match “${state.filter}” right now.`;markerByNum.forEach((m,n)=>{const x=listings.find(v=>v.num===n);if(x&&matchFilter(x))m.addTo(map);else map.removeLayer(m)});wireCards()}
function wireCards(){document.querySelectorAll('[data-card]').forEach(card=>{const n=+card.dataset.card;card.addEventListener('click',e=>{if(e.target.closest('button,a'))return;selectListing(n,true)});card.addEventListener('keydown',e=>{if(e.target!==card||!['Enter',' '].includes(e.key))return;e.preventDefault();selectListing(n,true)});card.addEventListener('mouseenter',()=>linkPair(n,true));card.addEventListener('mouseleave',()=>linkPair(n,false));card.addEventListener('focus',()=>linkPair(n,true));card.addEventListener('blur',()=>linkPair(n,false))});document.querySelectorAll('[data-route]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleRoute(+b.dataset.route)})}
function linkPair(n,on){if(matchMedia('(pointer:fine)').matches){document.querySelector(`[data-card="${n}"]`)?.classList.toggle('is-linked',on);markerByNum.get(n)?.getElement()?.querySelector('.pin')?.classList.toggle('is-linked',on)}}
function selectListing(n,scroll=false){state.selected=n;markerByNum.forEach((m,num)=>m.getElement()?.querySelector('.pin')?.classList.toggle('is-selected',num===n));document.querySelectorAll('[data-card]').forEach(c=>c.classList.toggle('is-selected',+c.dataset.card===n));renderPeek(n);if(scroll&&innerWidth<1024)document.querySelector(`[data-card="${n}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})}
function renderPeek(n){const x=listings.find(v=>v.num===n);if(!x)return;const onRoute=state.route.includes(n),peek=document.getElementById('mapPeek');peek.innerHTML=`<div class="card__pin">${pinHTML(x.num)}</div><div class="map-peek__meta"><strong>${x.name}</strong><small>${x.town}${x.times?' · '+x.times:''}</small></div><button class="btn btn--route" type="button" data-peek-route="${n}" aria-pressed="${onRoute}">${onRoute?'Added ✓':'+ Add'}</button>`;peek.classList.remove('is-hidden');peek.querySelector('[data-peek-route]').onclick=()=>toggleRoute(n)}
function toggleRoute(n){state.route=state.route.includes(n)?state.route.filter(x=>x!==n):[...state.route,n];try{localStorage.setItem('hfroute:2026',JSON.stringify(state.route))}catch{}renderCards();renderRoute();renderPeek(state.selected);markerByNum.forEach((m,num)=>m.getElement()?.querySelector('.pin')?.classList.toggle('is-on-route',state.route.includes(num)))}

function renderRoute(){document.getElementById('mobileRouteBar').classList.toggle('is-hidden',!state.route.length);document.getElementById('mobileRouteCount').textContent=`${state.route.length} stop${state.route.length===1?'':'s'} selected`;const stops=state.route.map(n=>listings.find(x=>x.num===n));const planner=document.getElementById('routePlanner');planner.innerHTML=`<div><p class="route__helper">Tap “Add to Route” on any display. Stops are visited in the order you add them.</p><div class="route__label" style="margin-top:14px">Starting from</div><div class="seg" role="radiogroup" aria-label="Starting point"><button type="button" data-mode="current" aria-checked="${state.startMode==='current'}">My location</button><button type="button" data-mode="address" aria-checked="${state.startMode==='address'}">Enter address</button></div>${state.startMode==='current'?`<div class="current-note" style="margin-top:10px"><span class="current-dot"></span>Your phone will ask to share your location</div>`:`<input class="route__input" id="startAddr" value="${state.startAddr.replaceAll('"','&quot;')}" placeholder="Enter your starting address" style="margin-top:10px">`}</div><div><div class="route__label">Your stops (${stops.length})</div><div class="stops" style="margin-top:8px">${stops.length?stops.map((s,i)=>`<div class="stop"><span class="stop__order">${i+1}</span><div class="stop__meta"><strong>${s.name}</strong><small>${s.town}</small></div><button type="button" class="stop__remove" data-remove="${s.num}" aria-label="Remove ${s.name}">×</button></div>`).join(''):`<div class="empty"><strong>No stops yet</strong><span>Add a display to start planning your route.</span></div>`}</div><button class="btn btn--map-route" id="mapRouteBtn" type="button" aria-disabled="${stops.length===0}" style="margin-top:12px">Map My Route</button><div style="margin-top:8px;color:var(--mist);font-size:14px">${stops.length} stop${stops.length===1?'':'s'} · opens driving directions in Google Maps${stops.length>10?' · Google Maps supports up to 10 stops':''}</div></div>`;planner.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.startMode=b.dataset.mode;renderRoute()});planner.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>toggleRoute(+b.dataset.remove));planner.querySelector('#startAddr')?.addEventListener('input',e=>state.startAddr=e.target.value);planner.querySelector('#mapRouteBtn').onclick=buildRoute}
function buildRoute(){const stops=state.route.map(n=>listings.find(x=>x.num===n));if(!stops.length)return;const capped=stops.slice(0,10),last=capped.at(-1),wps=capped.slice(0,-1).map(x=>x.address).join('|');const p=new URLSearchParams({api:'1',travelmode:'driving',destination:last.address});if(wps)p.set('waypoints',wps);if(state.startMode==='address'&&state.startAddr.trim())p.set('origin',state.startAddr.trim());window.open(`https://www.google.com/maps/dir/?${p.toString()}`,'_blank','noopener')}

async function geocodeAddress(address){if(address==='20 Tinc Rd, Flanders, NJ')return {lat:40.848065557922,lng:-74.721123548723};const key='hfgeo:'+address;const cached=localStorage.getItem(key);if(cached)return JSON.parse(cached);const url='https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=us&q='+encodeURIComponent(address);const r=await fetch(url,{headers:{Accept:'application/json'}});const d=await r.json();if(!d.length)throw new Error('Not found: '+address);const out={lat:+d[0].lat,lng:+d[0].lon};localStorage.setItem(key,JSON.stringify(out));await new Promise(r=>setTimeout(r,1050));return out}
async function loadMarkers(){const bounds=[];for(const x of listings){try{const c=await geocodeAddress(x.address);state.coords[x.num]=c;const m=L.marker([c.lat,c.lng],{icon:iconFor(x.num),keyboard:true,title:`Display ${x.num}: ${x.name}`,zIndexOffset:100+x.num}).addTo(map);m.on('click',()=>{selectListing(x.num,true)});m.on('mouseover',()=>linkPair(x.num,true));m.on('mouseout',()=>linkPair(x.num,false));markerByNum.set(x.num,m);bounds.push([c.lat,c.lng])}catch(err){console.warn(err)}}if(bounds.length)map.fitBounds(bounds,{padding:[40,40]});setTimeout(()=>map.invalidateSize(),100)}

document.getElementById('filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.dataset.filter;renderFilters();renderCards()});document.getElementById('showAllBtn').onclick=()=>{state.filter='All';renderFilters();renderCards()};document.getElementById('shareBtn').onclick=async()=>{const b=document.getElementById('shareBtn'),payload={title:'Halloween Display & Haunt Finder',text:'Find Halloween displays and home haunts around Mount Olive and the surrounding area.',url:location.href};try{if(navigator.share)await navigator.share(payload);else{await navigator.clipboard.writeText(location.href);b.textContent='Link copied';setTimeout(()=>b.textContent='Share',2000)}}catch{}};
renderFilters();renderCards();renderRoute();loadMarkers();
