const houseShareDialog=document.getElementById('houseShareDialog');
let sharedHouse=null;
function houseLink(house){return 'https://hauntfinder.vercel.app/?house='+house.num}
function housePost(house){return `We're on the 2026 Halloween Haunt Finder!\n\nVisit ${house.name}\n${house.address}\n${[house.dates,house.times].filter(Boolean).join(' · ')||'Check the listing for viewing details.'}\n\nSee our listing: ${houseLink(house)}\nFind nearby displays and build your driving route: https://hauntfinder.vercel.app/\nHave a display to add or update? ${FORM_URL}\n\n#MountOliveNJ #Halloween2026 #HauntFinder`}
function listingImage(house){
  const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1080;const c=canvas.getContext('2d');
  c.fillStyle='#100b1e';c.fillRect(0,0,1080,1080);c.strokeStyle='#7837cf';c.lineWidth=8;c.strokeRect(28,28,1024,1024);
  c.fillStyle='#b2e51a';c.font='bold 28px sans-serif';c.fillText('MOUNT OLIVE & SURROUNDING AREA • 2026',70,100);
  c.fillStyle='#ff8614';c.font='bold 68px sans-serif';c.fillText('HALLOWEEN',70,192);c.fillStyle='#f5ecd1';c.font='bold 40px sans-serif';c.fillText('DISPLAY & HAUNT FINDER',70,250);
  function lines(text,y,size,color,maxLines=3){c.font=`${size}px sans-serif`;c.fillStyle=color;const words=String(text).split(/\s+/);let line='',count=0;for(const word of words){const next=line?line+' '+word:word;if(c.measureText(next).width>930&&line){if(++count>=maxLines){while(c.measureText(line+'…').width>930)line=line.slice(0,-1);c.fillText(line+'…',70,y);return y+size*1.3}c.fillText(line,70,y);y+=size*1.3;line=word}else line=next}if(line){while(c.measureText(line).width>930)line=line.slice(0,-2)+'…';c.fillText(line,70,y);y+=size*1.3}return y}
  let y=lines(house.name,370,52,'#ff8614',2);y=lines(house.address,y+25,34,'#f5ecd1',2);y=lines([house.dates,house.times].filter(Boolean).join(' · ')||'Check the site for viewing details',y+35,30,'#f5ecd1',3);lines([...house.levels,...house.type].join(' · '),y+35,28,'#b2e51a',2);
  c.fillStyle='#7837cf';c.fillRect(70,875,940,3);c.fillStyle='#f5ecd1';c.font='bold 34px sans-serif';c.fillText('Find this house. Plan your route.',70,940);c.font='32px sans-serif';c.fillText('hauntfinder.vercel.app/?house='+house.num,70,994);
  return canvas.toDataURL('image/png');
}
function openHouseShare(id){const house=listings.find(x=>x.num===id);if(!house)return;sharedHouse=house;document.getElementById('houseShareText').value=housePost(house);document.getElementById('houseShareStatus').textContent='';const url=listingImage(house);document.getElementById('houseShareImage').src=url;const download=document.getElementById('downloadHouseImage');download.href=url;download.download='hauntfinder-house-'+id+'-2026.png';houseShareDialog.showModal()}
document.getElementById('cardList').addEventListener('click',e=>{const button=e.target.closest('[data-share-house]');if(button)openHouseShare(+button.dataset.shareHouse)});
document.getElementById('copyHousePost').onclick=async()=>{const text=document.getElementById('houseShareText');try{await navigator.clipboard.writeText(text.value);document.getElementById('houseShareStatus').textContent='Post copied. Paste it into your social app and attach the saved image.'}catch{text.focus();text.select();document.getElementById('houseShareStatus').textContent='Select and copy the suggested post above.'}};
document.getElementById('shareHousePost').onclick=async()=>{if(!sharedHouse)return;if(!navigator.share){document.getElementById('copyHousePost').click();return}try{await navigator.share({title:sharedHouse.name,text:housePost(sharedHouse)});}catch(e){if(e.name!=='AbortError')document.getElementById('houseShareStatus').textContent='Use Copy post and Save listing image to share.'}};
const linkedHouse=Number(new URLSearchParams(location.search).get('house'));if(listings.some(x=>x.num===linkedHouse)){selectListing(linkedHouse);document.querySelector(`[data-card="${linkedHouse}"]`)?.scrollIntoView({block:'center'});}
